/**
 * The contracts that outlive a release.
 *
 * Three things here can never be broken quietly, because artifacts are
 * immutable and `rollback` can reactivate one built any time: the manifest a
 * stored artifact was validated against, the wire a compiled prelude speaks to
 * the broker, and the on-disk shape of a storage resource whose data outlives
 * every redeploy.
 *
 * So this renders them to `CONTRACTS.md` and fails when the committed file is
 * stale — regenerate with `UPDATE_CONTRACTS=1 bun test`. The point is not the
 * document: it is that changing a frozen contract cannot happen without a
 * visible diff in a file whose header says what freezing means.
 */
import { expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { Database } from "bun:sqlite";
import { createBroker } from "./broker";
import { ARTIFACT_SCHEMA_VERSION, CAPABILITY_PROFILE, DEPLOY_TARGET, RUNTIME, validateManifest } from "./manifest";
import { EMPTY_BINDINGS, BASELINE_COMPATIBILITY_DATE } from "./wrap";
import { CONTROL_VERSION_HEADER, MIN_CLI_HEADER } from "./api-version";

const srcDir = import.meta.dir;
const root = resolve(srcDir, "..");
const read = (file: string) => readFileSync(resolve(srcDir, file), "utf8");

/**
 * Source text of a shared-package module. config.ts and manifest.ts moved to
 * @sproutboat/* (src/ files here are re-export shims), so the doc generator
 * reads the single source of truth from the linked packages.
 */
function pkgSource(pkg: string, file: string): string {
  return readFileSync(resolve(root, "node_modules", pkg, "src", file), "utf8");
}

/** All `case "op.name":` labels in the broker's dispatch — the switch is the truth. */
function brokerOps(): string[] {
  const source = read("broker.ts");
  return [...source.matchAll(/case "([a-z0-9_]+(?:\.[a-z0-9_]+)*)":/g)].map((m) => m[1]).sort();
}

/** Every table the broker creates, i.e. the shape a resource file is stuck with. */
function storageTables(): string[] {
  return [...read("broker.ts").matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map((m) => m[1]).sort();
}

/** Pull a quoted-string array/Set literal out of source text by its declaration. */
function stringListFrom(source: string, file: string, declaration: string): string[] {
  const start = source.indexOf(declaration);
  if (start === -1) throw new Error(`${file}: could not find ${declaration}`);
  const open = source.indexOf("[", start);
  const close = source.indexOf("]", open);
  return [...source.slice(open, close).matchAll(/"([^"]+)"/g)].map((m) => m[1]);
}

function render(): string {
  const rows = (cells: string[][]) => cells.map((r) => `| ${r.join(" | ")} |`).join("\n");
  const list = (items: string[]) => items.map((i) => `- \`${i}\``).join("\n");
  return [
    "# sproutboat — frozen contracts",
    "",
    "> Generated by `src/contracts.test.ts`. Do not edit by hand — run",
    "> `UPDATE_CONTRACTS=1 bun test`.",
    "",
    "A sprout is an immutable native binary, and `rollback` can reactivate one",
    "built arbitrarily long ago. So a broker must speak to every prelude ever",
    "compiled, a control plane must validate every manifest ever stored, and a",
    "storage file must stay readable by every later release. Everything below is",
    "**additive-only**: add a field, an op, a column; never remove or repurpose",
    "one. A change here that is not additive breaks deployed applications.",
    "",
    "Runtime behaviour is the exception, and it has its own escape hatch: gate it",
    `on \`__sbCompat\` (baseline \`${BASELINE_COMPATIBILITY_DATE}\`) so old binaries keep old semantics.`,
    "",
    "## Artifact manifest",
    "",
    rows([
      ["Field", "Value"],
      ["---", "---"],
      ["`schemaVersion`", `\`${ARTIFACT_SCHEMA_VERSION}\` — frozen`],
      ["`runtime`", `\`${RUNTIME}\``],
      ["`capabilityProfile`", `\`${CAPABILITY_PROFILE}\``],
      ["`target`", `\`${DEPLOY_TARGET}\``],
    ]),
    "",
    "Required fields:",
    "",
    list(stringListFrom(pkgSource("@sproutboat/artifact", "manifest.ts"), "manifest.ts", "const required = [")),
    "",
    "Optional fields (absent in artifacts built before they existed, and that",
    "must keep validating):",
    "",
    list(["compatibilityDate"]),
    "",
    "## Broker wire",
    "",
    "Frame envelope, both directions: `[u32 LE length][payload]`, where a request",
    'payload is `"<token>\\n<json>"` and a reply payload is `"<json>"`.',
    "",
    "Ops:",
    "",
    list(brokerOps()),
    "",
    "## Storage",
    "",
    "Tables in a resource file, which outlives every redeploy:",
    "",
    list(storageTables()),
    "",
    "## Binding kinds",
    "",
    list(Object.keys(EMPTY_BINDINGS).sort()),
    "",
    "## Project config",
    "",
    "Accepted `sproutboat.jsonc` keys. `validateConfig` rejects anything else, so",
    "adding a key makes new configs unreadable by older CLIs — additive here is",
    "still a compatibility event.",
    "",
    list(stringListFrom(pkgSource("@sproutboat/config", "config.ts"), "config.ts", "const allowed = new Set([")),
    "",
    "## Version handshake",
    "",
    "Headers on every `/api/` response from a control plane:",
    "",
    list([CONTROL_VERSION_HEADER, MIN_CLI_HEADER]),
    "",
  ].join("\n");
}

test("CONTRACTS.md is current", () => {
  const path = resolve(root, "CONTRACTS.md");
  const rendered = render();
  if (process.env.UPDATE_CONTRACTS) {
    writeFileSync(path, rendered);
    return;
  }
  const committed = readFileSync(path, "utf8");
  expect(committed).toBe(rendered);
});

test("an artifact manifest from before compatibilityDate still validates", () => {
  // Verbatim shape of a v2 manifest as shipped before this field existed. If
  // this ever fails, every stored artifact from that era has become
  // undeployable and `rollback` is broken for real users.
  const shipped = JSON.parse(readFileSync(resolve(root, "fixtures/manifest-pre-compat.json"), "utf8"));
  const result = validateManifest(shipped);
  expect(result.ok).toBe(true);
});

test("a storage resource written by v0.1.0 is still readable", async () => {
  // #74: a KV/R2/queue resource outlives redeploys, so its file outlives
  // releases too. Load a store dumped from the shipped broker and read it back
  // with today's code — if this fails, an upgrade silently orphaned real data.
  const dir = mkdtempSync(join(tmpdir(), "sb-contract-"));
  const id = "kv_0123456789abcdef01234567";
  const resourceDir = join(dir, "resources");
  mkdirSync(resourceDir, { recursive: true });
  const store = new Database(join(resourceDir, `${id}.sqlite`), { create: true });
  store.exec(readFileSync(resolve(root, "fixtures/store-kv-resource.sql"), "utf8"));
  store.close();

  const broker = createBroker({
    db: join(dir, "state.sqlite"),
    resourceDir,
    bindings: { kv: ["CACHE"], resources: { CACHE: { kind: "kv", id } } },
  });
  const reply = await broker.dispatch({ op: "kv.get", ns: "CACHE", key: "greeting" });
  broker.close();
  rmSync(dir, { recursive: true, force: true });

  expect(reply.found).toBe(true);
  expect(reply.value).toBe("hello from v0.1.0");
});

test("standalone storage creates the same additive trigger poll indexes", () => {
  const source = read("transport-embedded.js");
  expect(source).toContain("CREATE INDEX IF NOT EXISTS mq_due ON mq (queue, dead, visible_at)");
  expect(source).toContain("CREATE INDEX IF NOT EXISTS do_alarm_due ON do_alarm (at)");
});
