/**
 * The CLI describes itself. This test renders the command / env / toolchain
 * surface to `SURFACE.md` at the repo root and fails if the committed file is
 * stale — regenerate with `UPDATE_SURFACE=1 bun test`.
 *
 * It also cross-checks the source so the doc can't quietly drift:
 *   - every `case "x":` in main.ts's command switch is in COMMANDS, and vice versa
 *   - every SPROUTBOAT_* / PORFFOR_VERSION / XDG_CONFIG_HOME env read in src/
 *     (outside tests) is documented in ENV_VARS
 */
import { expect, test } from "bun:test";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CLI_NAME, COMMANDS, ENV_VARS, usageLine } from "./surface";
import { ARTIFACT_SCHEMA_VERSION, CAPABILITY_PROFILE, RUNTIME } from "./manifest";
import { ZIG_VERSION, toolchainStamp } from "./toolchain";

const srcDir = import.meta.dir;
const root = resolve(srcDir, "..");
const version = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")).version as string;

function render(): string {
  const rows = (cells: string[][]) => cells.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return [
    `# ${CLI_NAME} — surface`,
    "",
    "> Generated by `src/surface.test.ts` from `src/surface.ts` + the pinned",
    "> toolchain constants. Do not edit by hand — run `UPDATE_SURFACE=1 bun test`.",
    "",
    `**Package:** \`sproutboat\` ${version} · runs on Bun (use \`bunx\`, not \`npx\`)`,
    "",
    "## Commands",
    "",
    "| Command | Arguments | Summary |",
    "| --- | --- | --- |",
    rows(COMMANDS.map((c) => [`\`${c.name}\``, c.args ? `\`${c.args}\`` : "—", c.summary])),
    "",
    "```",
    usageLine(),
    "```",
    "",
    "## Environment variables",
    "",
    "| Variable | Purpose |",
    "| --- | --- |",
    rows(ENV_VARS.map((e) => [`\`${e.name}\``, e.purpose])),
    "",
    "## Build toolchain (pinned)",
    "",
    "| | |",
    "| --- | --- |",
    rows([
      ["Zig", `\`${ZIG_VERSION}\` (\`zig cc -target x86_64-linux-musl\`, static)`],
      ["Provenance stamp", `\`${toolchainStamp()}\``],
      ["Artifact schema", `\`${ARTIFACT_SCHEMA_VERSION}\``],
      ["Runtime", `\`${RUNTIME}\``],
      ["Capability profile", `\`${CAPABILITY_PROFILE}\``],
    ]),
    "",
  ].join("\n");
}

const surfacePath = resolve(root, "SURFACE.md");

test("SURFACE.md is up to date", () => {
  const rendered = render();
  if (process.env.UPDATE_SURFACE === "1") {
    writeFileSync(surfacePath, rendered);
    return;
  }
  let onDisk = "";
  try { onDisk = readFileSync(surfacePath, "utf8"); } catch { /* missing -> fail below */ }
  expect(onDisk, "SURFACE.md is stale or missing — run `UPDATE_SURFACE=1 bun test`").toBe(rendered);
});

test("the command switch and COMMANDS agree", () => {
  const main = readFileSync(resolve(srcDir, "main.ts"), "utf8");
  const switched = new Set([...main.matchAll(/case "([a-z-]+)":/g)].map((m) => m[1]));
  const documented = new Set(COMMANDS.map((c) => c.name));
  expect([...switched].sort()).toEqual([...documented].sort());
});

test("every env var read in src/ is documented in ENV_VARS", () => {
  const documented = new Set(ENV_VARS.map((e) => e.name));
  const seen = new Set<string>();
  for (const file of readdirSync(srcDir)) {
    if (!file.endsWith(".ts") || file.endsWith(".test.ts")) continue;
    const text = readFileSync(resolve(srcDir, file), "utf8");
    for (const m of text.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)/g)) {
      const name = m[1];
      // internal/plumbing vars that aren't part of the user-facing contract
      if (name === "PATH" || name === "HOME") continue;
      seen.add(name);
    }
  }
  const undocumented = [...seen].filter((name) => !documented.has(name));
  expect(undocumented, `undocumented env vars: ${undocumented.join(", ")}`).toEqual([]);
});

test("no COMMANDS entry documents an env var that src/ never reads", () => {
  const referenced = new Set<string>();
  for (const file of readdirSync(srcDir)) {
    if (!file.endsWith(".ts") || file.endsWith(".test.ts")) continue;
    const text = readFileSync(resolve(srcDir, file), "utf8");
    for (const m of text.matchAll(/([A-Z][A-Z0-9_]{3,})/g)) referenced.add(m[1]);
  }
  const stale = ENV_VARS.map((e) => e.name).filter((name) => !referenced.has(name));
  expect(stale, `ENV_VARS lists names not found anywhere in src/: ${stale.join(", ")}`).toEqual([]);
});
