import { expect, test } from "bun:test";
import { parseConfig } from "./config";
import { generateTypes, TYPES_FILE } from "./types-gen";

const config = (extra: string) => {
  const parsed = parseConfig(
    `{ "name": "demo", "main": "src/index.js", "compatibility_date": "2026-09-07", ${extra} }`,
  );
  if (!parsed.ok) throw new Error(parsed.errors.join("; "));
  return parsed.value;
};

test("every binding kind reaches env with its own type", () => {
  const out = generateTypes(
    config(`
      "vars": { "SITE": "demo" },
      "secrets": ["ADMIN_TOKEN"],
      "kv_namespaces": ["SESSIONS"],
      "d1_databases": ["DB"],
      "r2_buckets": ["UPLOADS"],
      "queues": ["EMAILS"],
      "analytics_engine_datasets": ["METRICS"],
      "durable_objects": { "VIEWS": "ViewCounter" },
      "services": [{ "binding": "PEER", "service": "other" }],
      "assets": { "directory": "public", "binding": "ASSETS" }
    `),
  );
  expect(out).toContain("SITE: string;");
  expect(out).toContain("ADMIN_TOKEN: string;");
  expect(out).toContain("SESSIONS: KVNamespace;");
  expect(out).toContain("DB: D1Database;");
  expect(out).toContain("UPLOADS: R2Bucket;");
  expect(out).toContain("EMAILS: Queue;");
  expect(out).toContain("METRICS: AnalyticsEngineDataset;");
  expect(out).toContain("VIEWS: DurableObjectNamespace;");
  expect(out).toContain("PEER: Fetcher;");
  expect(out).toContain("ASSETS: Fetcher;");
});

test("bindings declared with an id are read by binding name, not id", () => {
  // `{ binding, id }` is the pinned form deploy writes back into the config.
  const out = generateTypes(
    config(`"kv_namespaces": [{ "binding": "SESSIONS", "id": "kv_0123456789abcdef01234567" }]`),
  );
  expect(out).toContain("SESSIONS: KVNamespace;");
  expect(out).not.toContain("kv_0123456789abcdef01234567");
});

test("the file references the shipped ambient types and declares env as a global", () => {
  const out = generateTypes(config(`"kv_namespaces": ["KV"]`));
  expect(out).toContain('/// <reference types="sproutboat/types" />');
  expect(out).toContain("declare global {");
  expect(out).toContain("const env: {");
  // env is a global here, so nothing may suggest a parameter.
  expect(out).not.toContain("fetch(request, env");
});

test("a project with no bindings still produces a valid file", () => {
  const out = generateTypes(config(`"vars": {}`));
  expect(out).toContain("const env: {");
  expect(out).toContain("No bindings declared");
});

test("the generated file says it is generated, and names itself", () => {
  expect(generateTypes(config(`"kv_namespaces": ["KV"]`))).toStartWith("// Generated by `sproutboat types`.");
  expect(TYPES_FILE).toBe("sproutboat-env.d.ts");
});
