/**
 * `sproutboat types` — the project's `env`, as TypeScript.
 *
 * In Workers `env` is a parameter, so an editor can infer it from a signature.
 * Here it is a global, which means nothing is inferable at all: `env.SESSIONS`
 * is an undeclared identifier until this file exists. That makes generated
 * types worth more here than they are there, not less.
 *
 * The output declares `env` from `sproutboat.jsonc` and references the ambient
 * types shipped in `types/sproutboat.d.ts`, so binding *shapes* version with
 * the CLI and binding *names* version with the project.
 *
 * Names need no quoting: `parseConfig` already holds every binding and var to
 * /^[A-Z][A-Z0-9_]*$/, so all of them are plain identifiers.
 */
import { resourceRefs, type SproutboatConfig } from "./config";

/** The file the generator writes, relative to the project directory. */
export const TYPES_FILE = "sproutboat-env.d.ts";

const HEADER = `// Generated by \`sproutboat types\`. Do not edit.
//
// Regenerated whenever sproutboat.jsonc is newer than this file, so a binding
// added to the config shows up in the editor without asking. Commit it: it is
// part of the project's type surface, like a schema.
`;

type Entry = { name: string; type: string; note?: string };

function entries(config: SproutboatConfig): Entry[] {
  const out: Entry[] = [];

  for (const [name, value] of Object.entries(config.vars ?? {})) {
    out.push({ name, type: "string", note: `vars: ${JSON.stringify(value)}` });
  }
  for (const name of config.secrets ?? []) {
    out.push({ name, type: "string", note: "secret, set with `sproutboat secrets set`" });
  }
  for (const { binding } of resourceRefs(config.kv_namespaces)) out.push({ name: binding, type: "KVNamespace" });
  for (const { binding } of resourceRefs(config.d1_databases)) out.push({ name: binding, type: "D1Database" });
  for (const { binding } of resourceRefs(config.r2_buckets)) out.push({ name: binding, type: "R2Bucket" });
  for (const { binding } of resourceRefs(config.queues)) out.push({ name: binding, type: "Queue" });
  for (const name of config.analytics_engine_datasets ?? []) {
    out.push({ name, type: "AnalyticsEngineDataset" });
  }
  for (const [binding, className] of Object.entries(config.durable_objects ?? {})) {
    out.push({ name: binding, type: "DurableObjectNamespace", note: `class ${className}` });
  }
  for (const service of config.services ?? []) {
    out.push({ name: service.binding, type: "Fetcher", note: `service binding: ${service.service}` });
  }
  for (const rl of config.ratelimiters ?? []) {
    out.push({ name: rl.binding, type: "RateLimit", note: `rate limit: ${rl.limit} per ${rl.period}s` });
  }
  if (config.assets?.binding) {
    out.push({ name: config.assets.binding, type: "Fetcher", note: `static assets: ${config.assets.directory}` });
  }
  return out;
}

/**
 * The contents of `sproutboat-env.d.ts` for `config`.
 *
 * Pure, so the test can assert on the text and `dev` can compare it against
 * what is already on disk without writing.
 */
export function generateTypes(config: SproutboatConfig): string {
  const rows = entries(config);
  const body = rows.length
    ? rows
        .map((entry) => `    ${entry.note ? `/** ${entry.note} */\n    ` : ""}${entry.name}: ${entry.type};`)
        .join("\n")
    : "    // No bindings declared in sproutboat.jsonc yet.";

  return `${HEADER}
/// <reference types="sproutboat/types" />

declare global {
  /**
   * Bindings from sproutboat.jsonc, for project "${config.name}".
   *
   * A global, not a parameter: the handler signature is \`fetch(request)\`.
   * Every call on these is synchronous, so \`await\` is allowed and does
   * nothing.
   */
  const env: {
${body}
  };
}

export {};
`;
}
